import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      // Generated by Next.js on every build; its triple-slash references are
      // required there and cannot be rewritten as imports.
      "next-env.d.ts",
      // MongoDB VS Code playgrounds. They run inside mongosh, not Node, so
      // their globals (`use`, `db`) are undefined here — and `use()` in
      // particular is misread as React's `use` hook.
      "*.mongodb.js",
    ],
  },
];

export default eslintConfig;
